import { DefaultTheme } from 'styled-components';

const deviceSizes = {
  mobile: '480px',
  tablet: '768px',
  laptop: '1024px',
  desktop: '1200px',
};

const device = {
  mobile: `screen and (max-width: ${deviceSizes.mobile})`,
  tablet: `screen and (max-width: ${deviceSizes.tablet})`,
  laptop: `screen and (max-width: ${deviceSizes.laptop})`,
  desktop: `screen and (max-width: ${deviceSizes.desktop})`,
};

export const theme: DefaultTheme = {
  device,
};

export const COLORS = {
  black: '#130d08',
  yellow: '#FFD43B',
  green: '#00D749',
  red: '#FF2E00',
  white: '#ffffff',
  lightBrown: {
    100: '#f9f3ed',
    200: '#f3e6dc',
    300: '#eddaca',
    400: '#e7ceb8',
    500: '#e1c2a7',
    600: '#dab595',
    700: '#d4a983',
    800: '#ce9d71',
    900: '#c89060',
    1000: '#C2844E',
  },
  deepBrown: {
    0: '#C2844E',
    100: '#af7746',
    200: '#9b6a3e',
    300: '#885c37',
    400: '#744f2f',
    500: '#614227',
    600: '#4e351f',
    700: '#3a2817',
    800: '#271a10',
    900: '#130d08',
    1000: '#000000',
  },
  grayscale: {
    100: '#f5f5f5',
    200: '#dbdbdb',
    300: '#c2c2c2',
    400: '#a8a8a8',
    500: '#8f8f8f',
    600: '#757575',
    700: '#5c5c5c',
    800: '#424242',
    900: '#292929',
  },
};

export const ICONS = {
  add: require('@/assets/icons/ic-add.png'),
  bread1: require('@/assets/icons/ic-bread1.png'),
  bread2: require('@/assets/icons/ic-bread2.png'),
  bread3: require('@/assets/icons/ic-bread3.png'),
  bread4: require('@/assets/icons/ic-bread4.png'),
  bread5: require('@/assets/icons/ic-bread5.png'),
  bread6: require('@/assets/icons/ic-bread6.png'),
  checkLarge: require('@/assets/icons/ic-check-large.png'),
  check: require('@/assets/icons/ic-check.png'),
  leftArrow: require('@/assets/icons/ic-left-arrow.png'),
  reviewStar: require('@/assets/icons/ic-review-star.png'),
  reviewStarHalf: require('@/assets/icons/ic-review-star-half.png'),
  share: require('@/assets/icons/ic-share.png'),
  myLocation: require('@/assets/icons/ic-my-location.png'),
  store1: require('@/assets/icons/ic-store1.png'),
  store2: require('@/assets/icons/ic-store2.png'),
  backspace: require('@/assets/icons/ic-backspace.png'),
  address: require('@/assets/icons/ic-address.png'),
  addressActive: require('@/assets/icons/ic-address-active.png'),
  home: require('@/assets/icons/ic-home.png'),
  homeActive: require('@/assets/icons/ic-home-active.png'),
  search: require('@/assets/icons/ic-search.png'),
  searchActive: require('@/assets/icons/ic-search-active.png'),
  content: require('@/assets/icons/ic-content.png'),
  contentActive: require('@/assets/icons/ic-content-active.png'),
  like: require('@/assets/icons/ic-like.png'),
  likeActive: require('@/assets/icons/ic-like-active.png'),
  my: require('@/assets/icons/ic-my.png'),
  myActive: require('@/assets/icons/ic-my-active.png'),
  mypageLocation: require('@/assets/icons/my/ic-location.png'),
  mypageEmoji: require('@/assets/icons/my/ic-emoji.png'),
  mypageNotice: require('@/assets/icons/my/ic-notice.png'),
  mypageReview: require('@/assets/icons/my/ic-review.png'),
  mypageAlter: require('@/assets/icons/my/ic-alter.png'),
};
